### ISSUE TITLE
IT18921_DAnnunzio_L-Innocente and IT18921_Svevo_Una-vita have same id

### ISSUE THREAD

**Issue by morethanbooks** [COST-ELTeC/ELTeC-ita#6]
Hi there! I think I have found an error. The following files have the same id:

- IT18921_DAnnunzio_L-Innocente
- IT18921_Svevo_Una-vita

This appears also in the xml:id of the TEI element of both files (="IT18921").
Regards!

**Comment by lb42** [comment]
Thanks for reporting this error Jose. I have no idea how it got through the validation, but it's fixed now.
